# Generated by Django 3.2.6 on 2021-08-21 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Messages', '0003_auto_20210821_1108'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Data',
            new_name='Data_msg',
        ),
    ]
