# Generated by Django 3.2.6 on 2021-08-21 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messages', '0004_rename_data_data_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_msg',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
